# Generated by Django 6.0.2 on 2026-02-07 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='valuer',
            new_name='value',
        ),
    ]
