# Generated by Django 6.0.2 on 2026-02-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_brand_alter_bike_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='bikes/'),
        ),
    ]
